---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "externalDNS.fullname" . }}
  labels:
    {{- include "externalDNS.labels" . | nindent 4 }}
data:
  EXTERNAL_DNS_PROVIDER: pdns
  EXTERNAL_DNS_PDNS_SERVER: http://{{ include "pdns.fullname" . }}-http
  EXTERNAL_DNS_PDNS_API_KEY: {{ .Values.pdns.config.apiKey }}
  {{- with .Values.externalDNS.extraConfig }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
