---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "externalDNS.fullname" . }}-{{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
{{- if default false .Values.externalDNS.sourceIstioObjects }}
- apiGroups: ["networking.istio.io"]
  resources: ["gateways", "virtualservices"]
  verbs: ["get","watch","list"]
{{- end }}
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
