---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pdns.fullname" . }}-config
  labels:
    {{- include "pdns.labels" . | nindent 4 }}
data:
  pdns.conf: |
    launch=gsqlite3
    gsqlite3-database=/data/db

    {{- if .Values.pdns.httpService.enabled }}
    webserver=yes
    webserver-address=0.0.0.0
    webserver-port=80

    api=yes
    api-key={{ .Values.pdns.config.apiKey }}

    webserver-allow-from=0.0.0.0/0
    {{- end}}
    {{- range $key, $value := .Values.pdns.extraConfig }}
    {{ $key }}={{ $value }}
    {{- end }}
