{{- if .Values.pdns.udpService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.pdns.udpService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "pdns.fullname" . }}-dns-udp
  labels:
    {{- include "pdns.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.pdns.udpService.port }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "pdns.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.pdns.tcpService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.pdns.tcpService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "pdns.fullname" . }}-dns-tcp
  labels:
    {{- include "pdns.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.pdns.tcpService.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "pdns.selectorLabels" . | nindent 4 }}
{{- end }}